export const ALL_JOBS_REQUEST = "ALL_JOBS_REQUEST";
export const ALL_JOBS_SUCCESS = "ALL_JOBS_SUCCESS";
export const ALL_JOBS_FAIL = "ALL_JOBS_FAIL";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";

export const ADMIN_JOBS_REQUEST = "ADMIN_JOBS_REQUEST";
export const ADMIN_JOBS_SUCCESS = "ADMIN_JOBS_SUCCESS";
export const ADMIN_JOBS_FAIL = "ADMIN_JOBS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_RESET = "DELETE_JOB_RESET";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";

export const NEW_JOB_REQUEST = "NEW_JOB_REQUEST";
export const NEW_JOB_SUCCESS = "NEW_JOB_SUCCESS";
export const NEW_JOB_RESET = "NEW_JOB_RESET";
export const NEW_JOB_FAIL = "NEW_JOB_FAIL";

export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_RESET = "UPDATE_JOB_RESET";
export const UPDATE_JOB_FAIL = "UPDATE_JOB_FAIL";

export const UPLOAD_RESUME_REQUEST = "UPLOAD_RESUME_REQUEST";
export const UPLOAD_RESUME_SUCCESS = "UPLOAD_RESUME_SUCCESS";
export const UPLOAD_RESUME_RESET = "UPLOAD_RESUME_RESET";
export const UPLOAD_RESUME_FAIL = "UPLOAD_RESUME_FAIL";